trigger:
- main

pool:
#  vmImage: ubuntu-latest
  name: Default
  
stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - powershell: echo "Build FirstJob"
  - job: SecondJob
    steps:
    - powershell: echo "Build SecondJob"
- stage: Dev
  jobs:
  - job: DevDeployJob
    steps:
    - powershell: echo "Build DevDeployJob"
- stage: QA
  jobs:
  - job: QADeployJob
    steps:
    - powershell: echo "Build QADeployJob"
- stage: Prod
  jobs:
  - job: ProdDeployJob
    steps:
    - powershell: echo "Build ProdDeployJob"
